\c postgres
DROP DATABASE IF EXISTS devsnestbackend;
CREATE DATABASE devsnestbackend;
\c devsnestbackend
DROP TABLE IF EXISTS Datatypes;
CREATE TABLE Datatypes (
    MY_ID BIGSERIAL PRIMARY KEY NOT NULL ,
    FIRST_NAME VARCHAR(15) NOT NULL,
    LAST_NAME VARCHAR(15) DEFAULT 'KUMAR',
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    DOB DATE NOT NULL,
    INDIAN BOOLEAN NOT NULL,
    CONTECT_NO BIGINT NOT NULL,
    MARKS REAL NOT NULL,
    SALARY DECIMAL DEFAULT '0.00',
    TODAY CHAR(3) NOT NULL,
    CURRUNT_TIME TIME DEFAULT NOW()
);
INSERT INTO Datatypes (FIRST_NAME,LAST_NAME ,EMAIL ,DOB,INDIAN ,CONTECT_NO ,MARKS ,SALARY ,TODAY ,CURRUNT_TIME ) VALUES ('SURSESH','KUMAWAT','shunya@gmail.com',date '2001-02-23','YES',8823749392,86.40,15000,'MON',(SELECT NOW()::TIME));
INSERT INTO Datatypes (FIRST_NAME,EMAIL ,DOB,INDIAN ,CONTECT_NO ,MARKS ,SALARY ,TODAY ,CURRUNT_TIME ) VALUES ('SHUNYA','suresh@shunya.com',date '2001-09-30','y',8823743344,92.33,121000,'FRI',(SELECT NOW()::TIME));